JENKINS-63070 add multibranch project bitbucket link, updated copy slightly
jenkinsci/atlassian-bitbucket-server-integration-plugin pull request #246
Opened 2021-03-10 23:44 UTC by mhenschke-atl

Tracking issue: https://issues.jenkins.io/browse/JENKINS-63070
Addressing this feedback: https://github.com/jenkinsci/atlassian-bitbucket-server-integration-plugin/pull/192#discussion_r510781762

![Screenshot_20210311_103505](https://user-images.githubusercontent.com/53157896/110713560-3d2ba180-8256-11eb-9755-67ea7b6bc9ba.png)
Multibranch project viewer now has a "Browse repo" button, linking to the repository

![Screenshot_20210311_103521](https://user-images.githubusercontent.com/53157896/110713638-5c2a3380-8256-11eb-9a25-dcbfe4e6db09.png)
Projects generated by the multibranch project now show a "View branch" button, which links to the compare between branch and default branch

![Screenshot_20210311_103537](https://user-images.githubusercontent.com/53157896/110713705-7532e480-8256-11eb-9a9a-c3f9b88d291c.png)
Freestyle and pipeline jobs don't have branch information, so we link to the repo as usual.

2021-03-11 00:45 UTC, dkjellin requested changes
I'm going to request changes purely due to missing i18n.

2021-03-11 00:45 UTC, dkjellin commented on src/main/java/com/atlassian/bitbucket/jenkins/internal/link/BitbucketExternalLinkUtils.java
> +public class BitbucketExternalLinkUtils {
`@Since` maybe?

2021-03-11 00:45 UTC, dkjellin commented on src/main/java/com/atlassian/bitbucket/jenkins/internal/link/BitbucketExternalLinkUtils.java
> +    @Inject
do we need `@Inject` twice for effectively the same field? It is legal but it seems undesirable?

2021-03-11 00:45 UTC, dkjellin commented on src/main/java/com/atlassian/bitbucket/jenkins/internal/link/BitbucketLinkType.java
> +    REPO("Browse Repo");
May I propose we don't shorten this? so `Browse Repository` 

Also, these need to be i18n'ed right? So while this is simple here, I think we need to do something to look up the i18n strings. Either here or when we call the `getDisplayName`

2021-03-11 00:45 UTC, dkjellin commented on src/main/java/com/atlassian/bitbucket/jenkins/internal/link/BitbucketMultibranchLinkActionFactory.java
> +    @Inject
double injection annotations again, I think we only need one of these annotations?

2021-03-11 03:45 UTC, dkjellin approved these changes

2021-03-11 04:38 UTC, EliSalter-atl approved these changes

2021-03-11 05:55 UTC, dkjellin commented on src/main/java/com/atlassian/bitbucket/jenkins/internal/link/BitbucketExternalLinkUtils.java
> +    private BitbucketPluginConfiguration bitbucketPluginConfiguration;
totally up to you, but maybe move the `@Inject` to the constructor and remove the default constructor, that way you don't need two, and it should work (I imagine)

2021-03-11 19:29 UTC, KalleOlaviNiemitalo commented
We have a repository with long term support branches (e.g. `release/1.35`) and bugfix branches based on those (e.g. `bugfix/1.35/DEMO-42`). Comparing such a bugfix branch to the default branch (`master`) is not useful at all.

* When the `bugfix/1.35/DEMO-42` branch of that repository is being built, Groovy code in Jenkinsfile guesses that the branch is intended to be merged to `release/1.35`, based on the naming convention. It then passes this information to the [`discoverGitReferenceBuild` step](https://www.jenkins.io/doc/pipeline/steps/git-forensics/#discovergitreferencebuild-discover-git-reference-build) so that the Warnings Next Generation plugin can check whether the `bugfix/1.35/DEMO-42` build causes any warnings that are not already in `release/1.35`. It would then be nice to add a sidebar hyperlink to a diff that compares `bugfix/1.35/DEMO-42` to `release/1.35`.

* When the `release/1.35` branch of that repository is being built, Groovy code in Jenkinsfile guesses that the branch is not intended to be merged to anything, based on the naming convention. In this case, if a hyperlink to Bitbucket Server is added to the sidebar, it would be best for the link to refer just to the list of commits on that branch, not to any kind of comparison between branches.

I can think of several different ways to achieve this:

1. Make the Bitbucket Server Integration plugin define a pipeline step that Jenkinsfile can call to report the target branch, or `null` if no comparison should be made. Save this information to the Job, defaulting to `master` if Jenkinsfile does not call the pipeline step. Then generate different hyperlinks based on the saved information.

2. Make the Bitbucket Server Integration plugin search for an instance of [ReferenceBuild](<https://javadoc.jenkins.io/plugin/forensics-api/io/jenkins/plugins/forensics/reference/ReferenceBuild.html> "ReferenceBuild (Forensics API Plugin 1.0.0 API)") on a Run, and parse the branch from there. That has a few problems though:

   * The ReferenceBuild is stored in a Run but Bitbucket Server Integration would like to display a sidebar hyperlink on its parent Job.

   * If the ReferenceBuild refers to a Run that has been deleted, then the branch name may be difficult to extract using Jenkins APIs.

3. Make the Bitbucket Server Integration plugin define a way to prevent it from generating any sidebar hyperlinks. Jenkinsfile can then define its own hyperlinks via the [Sidebar Link](https://plugins.jenkins.io/sidebar-link/) plugin, which adds the hyperlinks to the parent Job of the Run on which it is used.

   I think I would prefer this last solution because the Jenkinsfile in version control would then be compatible with both Bitbucket Branch Source and Bitbucket Server Integration plugins, simplifying future migrations.

2021-04-13 00:49 UTC, mhenschke-atl commented
> We have a repository with long term support branches (e.g. `release/1.35`) and bugfix branches based on those (e.g. `bugfix/1.35/DEMO-42`). Comparing such a bugfix branch to the default branch (`master`) is not useful at all.

Thanks for explaining your use case here. It is however fairly specific and I have to ensure the shipped solution can be used generally. Given the wide variety of naming conventions used in repositories, I don't believe we can attempt to guess the destination branch based on that information alone. Ascertaining the target branch on a PR build will become more feasible if/when full support for PR builds in Jenkins appears, and at that point what your asking for is feasible. 

Defining custom pipeline steps and adding custom controls is well beyond the scope of this project, which is adding a convenience link so you can check the work being referred to in a build, so I'm afraid I don't intend on implementing this feature.

I still believe your original comment (https://issues.jenkins.io/browse/JENKINS-6307, which is what this PR implements) provides the best general use case on non-pr branches.

2021-05-16 22:59 UTC, merged